name: 03-Custom Javascript Action Pre Post Script
on:
   workflow_dispatch: 

jobs:
  Pre-Post-job:
    runs-on: ubuntu-latest
    name: A job to run Pre post scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Custom action step
        id: prepost
        uses: ./.github/actions/pre-post-custom-action        